docker-compose:
services:
  minio:
    image: quay.io/minio/minio
    restart: always
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server /data --console-address ":9090"
